#!/bin/bash

FILES=`git diff --cached --name-only | grep ".js"`
for FILE in $FILES ; do
    if [ "grep 'console.log' $FILE" ]
    then
        echo $FILE " has console.log's left. Please remove."
        exit 1
    fi
done
exit