#!/bin/bash
RESULT=0

case "${1}" in
    --about )
        echo "Validates JS files with jshint"
        ;;
    * )
		# Validate JS files
		echo "Validating JS files…"
		FILES=`git diff --cached --name-only | grep ".js"`
		for i in $FILES; do
			if [ -e $i ]
			then
				OUTPUT=`jshint $i`
				LINT=$?
				if [ $LINT != 0 ]
				then
					echo -e "\033[31m${OUTPUT}\033[m"
				fi
				RESULT=$((${LINT} || ${RESULT}))
			fi
		done
        ;;
esac

exit $RESULT