#!/bin/bash
RESULT=0

# Validate PHP files
echo "Validating PHP files…"
FILES=`git diff --cached --name-only | grep ".php"`
for i in $FILES; do
	OUTPUT=`php -l $i`
	LINT=$?
	if [ $LINT != 0 ]
	then
		echo -e "\033[31m${OUTPUT}\033[m"
	fi
	RESULT=$((${LINT} || ${RESULT}))
done;

exit $RESULT