#!/bin/bash
RESULT=0

case "${1}" in
    --about )
        echo "Validates PHP files with PHP Lint"
        ;;
    * )
		# Validate PHP files
		echo "Validating PHP files…"
		FILES=`git diff --cached --name-only | grep ".php"`
		for i in $FILES; do
			if [ -e $i ]
			then
				OUTPUT=`php -l $i`
				LINT=$?
				if [ $LINT != 0 ]
				then
					echo -e "\033[31m${OUTPUT}\033[m"
				fi
				RESULT=$((${LINT} || ${RESULT}))
			fi
		done
        ;;
esac

exit $RESULT